#pragma once

#define MENOETIUS_PORT 9001
#define MENOETIUS_METRIC_PORT 8001

#define MENOETIUS_RPC_PUT_DATA 3
#define MENOETIUS_RPC_GET_DATA 4
#define MENOETIUS_RPC_REPLICATION_DATA 7
#define MENOETIUS_RPC_QUERY_LFMS 8
#define MENOETIUS_RPC_GET_STATUS 9
#define MENOETIUS_RPC_GET_CLUSTER_CONFIG 10
#define MENOETIUS_RPC_SET_CLUSTER_CONFIG 11
#define MENOETIUS_RPC_REGISTER_CLIENT_CLUSTER_CONFIG 12
#define MENOETIUS_RPC_GET_VERSION 13

#define MENOETIUS_RPC_SET_CLOCK 98
#define MENOETIUS_RPC_TEST_HOOK 99

#define TEST_HOOK_SYNC_FLAG 0x01
#define TEST_HOOK_SHUTDOWN_FLAG 0x02

// equivalent to [153, 165, 63, 92] or [0x99 0xA5 0x3F 0x5C] (in little-endian)
#define MENOETIUS_RPC_MAGIC_HEADER 1547675033

// server response codes take up the first 7 bits
#define MENOETIUS_STATUS_OK 0
#define MENOETIUS_STATUS_TOO_MANY_POINTS 1
#define MENOETIUS_STATUS_TOO_MANY_METRICS 2
#define MENOETIUS_STATUS_NOT_FOUND 3
#define MENOETIUS_STATUS_UNKNOWN_ERROR 4
#define MENOETIUS_STATUS_MISSING_INDEX 5
#define MENOETIUS_SHUTTING_DOWN 6
#define MENOETIUS_STARTING_UP 7
#define MENOETIUS_STATUS_UNAUTHORIZED 8

// returned as a bit flag on response codes
#define MENOETIUS_CLUSTER_CONFIG_OUT_OF_DATE 0x80

// Errors
#define ERR_OK 0
#define ERR_OK_STR "ok"

#define ERR_UNKNOWN 1
#define ERR_UNKNOWN_STR "unknown error"

#define ERR_BITSTREAM_BAD_VALUE 2
#define ERR_BITSTREAM_BAD_VALUE_STR "bitstream bad value"

#define ERR_BITSTREAM_OUT_OF_SPACE 3
#define ERR_BITSTREAM_OUT_OF_SPACE_STR "bitstream out of space"

#define ERR_TSC_OUT_OF_SPACE 4
#define ERR_TSC_OUT_OF_SPACE_STR "tsc out of space"

#define ERR_TSC_UNKOWN 5
#define ERR_TSC_UNKOWN_STR "tsc unknown error"

#define ERR_TSC_ITER_DONE 6
#define ERR_TSC_ITER_DONE_STR "iterator done"

#define ERR_LOOKUP_FAILED 7
#define ERR_LOOKUP_FAILED_STR "lookup failed"

#define ERR_TOO_MANY_POINTS 8
#define ERR_TOO_MANY_POINTS_STR "too many points"

#define ERR_MEM_ALLOCATION 9
#define ERR_MEM_ALLOCATION_STR "memory allocation failure"

#define ERR_STRUCTURED_STREAM_BUF_TOO_SMALL 10
#define ERR_STRUCTURED_STREAM_BUF_TOO_SMALL_STR "ERR_STRUCTURED_STREAM_BUF_TOO_SMALL"

#define ERR_STRUCTURED_STREAM_BUF_NEED_MORE 11
#define ERR_STRUCTURED_STREAM_BUF_NEED_MORE_STR "ERR_STRUCTURED_STREAM_BUF_NEED_MORE"

#define ERR_STRUCTURED_STREAM_BUF_OTHER 12
#define ERR_STRUCTURED_STREAM_BUF_OTHER_STR "ERR_STRUCTURED_STREAM_BUF_OTHER"

#define ERR_STRUCTURED_STREAM_IO_REQUIRED 13
#define ERR_STRUCTURED_STREAM_IO_REQUIRED_STR "ERR_STRUCTURED_STREAM_IO_REQUIRED"

#define ERR_STRUCTURED_STREAM_EOF 14
#define ERR_STRUCTURED_STREAM_EOF_STR "ERR_STRUCTURED_STREAM_EOF"

#define ERR_STRUCTURED_STREAM_BUF_UNDERRUN 15
#define ERR_STRUCTURED_STREAM_BUF_UNDERRUN_STR "ERR_STRUCTURED_STREAM_BUF_UNDERRUN"

#define ERR_OUT_OF_ORDER_TIMESTAMP 16
#define ERR_OUT_OF_ORDER_TIMESTAMP_STR "ERR_OUT_OF_ORDER_TIMESTAMP"

#define ERR_BUF_TOO_SMALL 17
#define ERR_BUF_TOO_SMALL_STR "ERR_BUF_TOO_SMALL"

#define ERR_BAD_INDEX 18
#define ERR_BAD_INDEX_STR "ERR_BAD_INDEX"

const char* err_str( int err );

// FIXME this should be configurable, set to hold 24 hours worth since this is a PoC
#define MAX_PTS_PER_SERIES 86400

#define INVALID_KEY 0xFFFF

#define HASH_LENGTH 20
