#include "globals.h"

const char* err_str( int err )
{
	switch( err ) {
	case ERR_OK:
		return ERR_OK_STR;

	case ERR_UNKNOWN:
		return ERR_UNKNOWN_STR;

	case ERR_BITSTREAM_BAD_VALUE:
		return ERR_BITSTREAM_BAD_VALUE_STR;

	case ERR_BITSTREAM_OUT_OF_SPACE:
		return ERR_BITSTREAM_OUT_OF_SPACE_STR;

	case ERR_TSC_OUT_OF_SPACE:
		return ERR_TSC_OUT_OF_SPACE_STR;

	case ERR_TSC_UNKOWN:
		return ERR_TSC_UNKOWN_STR;

	case ERR_TSC_ITER_DONE:
		return ERR_TSC_ITER_DONE_STR;

	case ERR_LOOKUP_FAILED:
		return ERR_LOOKUP_FAILED_STR;

	case ERR_TOO_MANY_POINTS:
		return ERR_TOO_MANY_POINTS_STR;

	case ERR_MEM_ALLOCATION:
		return ERR_MEM_ALLOCATION_STR;

	case ERR_STRUCTURED_STREAM_BUF_TOO_SMALL:
		return ERR_STRUCTURED_STREAM_BUF_TOO_SMALL_STR;

	case ERR_STRUCTURED_STREAM_BUF_NEED_MORE:
		return ERR_STRUCTURED_STREAM_BUF_NEED_MORE_STR;

	case ERR_STRUCTURED_STREAM_BUF_OTHER:
		return ERR_STRUCTURED_STREAM_BUF_OTHER_STR;

	case ERR_STRUCTURED_STREAM_IO_REQUIRED:
		return ERR_STRUCTURED_STREAM_IO_REQUIRED_STR;

	case ERR_STRUCTURED_STREAM_EOF:
		return ERR_STRUCTURED_STREAM_EOF_STR;

	case ERR_STRUCTURED_STREAM_BUF_UNDERRUN:
		return ERR_STRUCTURED_STREAM_BUF_UNDERRUN_STR;

	case ERR_OUT_OF_ORDER_TIMESTAMP:
		return ERR_OUT_OF_ORDER_TIMESTAMP_STR;

	case ERR_BAD_INDEX:
		return ERR_BAD_INDEX_STR;

	default:
		return "unknown err number";
	}
}
